### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by McMartin**
Add the bare minimum to start the project in good conditions.

### CODE REVIEW

**Comment by McMartin** [comment]
@MartyLake: here we go!

**Comment by MartyLake** [comment]
LGTM !
Not a pro cmake dude, but I'm pretty sure it's not that difficult ;)

**Comment by McMartin** [comment]
As long as you read properly the docs, CMake is indeed not that difficult. But getting AppVeyor (CMake 3.1.2) and Travis CI (CMake 3.0.2, that I have to `brew upgrade` to 3.3.1) to work at the same time is really hard! :sweat_smile:

**Comment by MartyLake** [comment]
I can imagine that. GG WP :+1:

**Pull request merged**
